stages:
  - test
  - deploy

default:
  image: node:17.2.0
  before_script:
    - yarn install

lint-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - yarn lint
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - yarn build
    - echo "Application successfully deployed."
