stages:
  - setup
  - test
  - deploy

setup-job:
  stage: setup
  script:
    - echo "Setting up..."
    - apt-get update
    - export DEBIAN_FRONTEND=noninteractive
    - export TZ=US/Pacific
    - apt-get -y install npm sudo bash curl wget git gpg python3 xz-utils unzip zip
    - npm install --global n
    - n 17
    - npm install --global yarn
    - yarn install

lint-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - yarn lint
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - yarn build
    - echo "Application successfully deployed."
