#!/bin/bash

set -e

RESET='\033[0m'

BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'

if [[ "$@" =~ "-q" ]]; then
  QUIET=true
else
  QUIET=false
fi

if [ "$1" = "script" ]; then
    if [ "$2" = "create" ]; then
        if [ -z "$3" ]; then
            printf "${YELLOW}question ${CYAN}Script name: ${RESET}"
            read name
            printf "${YELLOW}question ${CYAN}Script action: ${RESET}"
            read syntax
            if [ "$QUIET" = false ]; then
                printf "${BLUE}info ${RESET}Creating script...${RESET}\n"
            fi
            node yarnx-scripts/script/create.js "name=$name" "action=$syntax" "dir=${PWD}"
            if [ "$QUIET" = false ]; then
                printf "${GREEN}success ${RESET}Script created!\n"
            fi
            exit 0
        else
            if [ -z "$4" ]; then
                printf "${YELLOW}question ${GREEN}Script action: ${RESET}"
                read syntax
                if [ "$QUIET" = false ]; then
                    printf "${BLUE}info ${RESET}Creating script...${RESET}\n"
                fi
                node yarnx-scripts/script/create.js "name=$3" "action=$syntax" "dir=${PWD}"
                if [ "$QUIET" = false ]; then
                    printf "${GREEN}success ${RESET}Script created!\n"
                fi
                exit 0
            else
                if [ "$QUIET" = false ]; then
                    printf "${BLUE}info ${RESET}Creating script...${RESET}\n"
                fi
                node yarnx-scripts/script/create.js "name=$3" "action=$4" "dir=${PWD}"
                if [ "$QUIET" = false ]; then
                    printf "${GREEN}success ${RESET}Script created!\n"
                fi
                exit 0
            fi
        fi
    elif [ "$2" = "delete" ]; then
        if [ -z "$3" ]; then
            printf "${YELLOW}question ${CYAN}Script name: ${RESET}"
            read name
            if [ "$QUIET" = false ]; then
                printf "${BLUE}info ${RESET}Deleting script...${RESET}\n"
            fi
            node yarnx-scripts/script/delete.js "name=$name" "dir=${PWD}"
            if [ "$QUIET" = false ]; then
                printf "${GREEN}success ${RESET}Script deleted!\n"
            fi
            exit 0
        else
            if [ "$QUIET" = false ]; then
                printf "${BLUE}info ${RESET}Deleting script...${RESET}\n"
            fi
            node yarnx-scripts/script/delete.js "name=$3" "dir=${PWD}"
            if [ "$QUIET" = false ]; then
                printf "${GREEN}success ${RESET}Script deleted!\n"
            fi
            exit 0
        fi
    elif [ "$2" = "run" ]; then
        if [ -z "$3" ]; then
            printf "${YELLOW}question ${CYAN}Script name: ${RESET}"
            read name
            if [ "$QUIET" = false ]; then
                printf "${BLUE}info ${RESET}Running script...${RESET}\n"
                yarn run $name
                printf "${GREEN}success ${RESET}Script ran!\n"
            else
                yarn run $name
            fi
            exit 0
        else
            if [ "$QUIET" = false ]; then
                printf "${BLUE}info ${RESET}Running script...${RESET}\n"
                yarn run $3
                printf "${GREEN}success ${RESET}Script ran!\n"
            else
                yarn run $3
            fi
            exit 0
        fi
    elif [ "$2" = "list" ]; then
        if [ "$QUIET" = false ]; then
            printf "${BLUE}info ${RESET}Listing scripts...${RESET}\n"
        fi
        node yarnx-scripts/script/list.js "dir=${PWD}"
        if [ "$QUIET" = false ]; then
            printf "${GREEN}success ${RESET}Scripts listed!\n"
        fi
        exit 0
    else
        printf "${RED}error ${RESET}Invalid argument!${RESET}\n"
        printf "${RESET}Usage:${RESET}\n"
        printf "  ${PURPLE}yarnx ${BLUE}script ${CYAN}create ${YELLOW}[name] [syntax]${RESET}\n"
        printf "  ${PURPLE}yarnx ${BLUE}script ${CYAN}delete ${YELLOW}[name]${RESET}\n"
        printf "  ${PURPLE}yarnx ${BLUE}script ${CYAN}run ${YELLOW}[name]${RESET}\n"
        printf "  ${PURPLE}yarnx ${BLUE}script ${CYAN}list${RESET}\n"
        exit 1
    fi
else
    yarn "$@"
fi
