version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test:
    docker:
      - image: node:17.3.1-buster
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            yarn install
            yarn lint
  build:
    docker:
      - image: ubuntu:focal
    steps:
      - checkout
      - run:
          name: Build stuff
          command: |
            apt-get update
            apt-get -y install sudo apt zip unzip
            apt-get -y upgrade
            curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
            apt-get install -y nodejs
            npm install --global yarn
            yarn install
            yarn build
            zip -r frontend.zip client/out
            zip -r api.zip api/dist
            zip -r backend.zip server/dist
            mkdir -p /tmp/artifacts
            mv frontend.zip api.zip backend.zip /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  test_app:
    jobs:
      - test
      - build
